### ISSUE TITLE
Dock icon not shown when run from within AppImage

### ISSUE THREAD

**Issue by probonopd** [probonopd/QtQuickApp#2]
On Ubuntu 16.04:

```
me@host:~$ sudo strace -eopen -f ./qtquickapp-git.bacf740-x86-64.appimage 2>&1 | grep pix
[pid  3517] open("/tmp/.mount_9gxq2L/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
[pid  3517] open("/tmp/.mount_9gxq2L/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
```

![screenshot from 2017-03-25 16-28-45](https://cloud.githubusercontent.com/assets/2480569/24323596/5217dd00-1178-11e7-9500-2fe9ea382091.png)

Strangely, when we extract the AppImage and run it then, then it works:

```
me@host:~$ ./qtquickapp-git.bacf740-x86-64.appimage --appimage-extract
me@host:~$ sudo strace -eopen -f squashfs-root/AppRun 2>&1 | grep pix
[pid  3710] open("/home/me/squashfs-root/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 6
[pid  3710] open("/home/me/squashfs-root/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 6
```

![screenshot from 2017-03-25 16-29-08](https://cloud.githubusercontent.com/assets/2480569/24323598/55ad37f8-1178-11e7-982c-3118daffb348.png)

I cannot currently explain this behaviour.

**Comment by crayxt** [comment]
Hi, it think it is an app icon, not tray icon? And I just tried Ubuntu 17.04 beta, and app icon appears just fine when run from appimage directly.

**Comment by probonopd** [comment]
Technically it is the icon of the window which we are setting [here](https://github.com/probonopd/QtQuickApp/blob/15a9c3893e80a7b0b4efdbf24c0c71df0b574bd5/main.cpp#L10).

**Comment by probonopd** [comment]
@crayxt out of curiosity, do you get `open() ... = 6` or `= 7` when you run the above commands?

**Comment by crayxt** [comment]
@probonopd It is much stranger now, when the appimage in ~ directory, app icon does not show up, but when launched from ~/Downloads, then it **does** appear. strace gives ```7``` for both cases.

**Comment by crayxt** [comment]
~~I mean when you launch appimage from regular DE, there is nothing in tray area, that's why I pointed out that it is not a **tray** icon.~~ Nevermind ;)

**Comment by probonopd** [comment]
Do you have `appimaged` running?

**Comment by crayxt** [comment]
Nope it is a live cd

**Comment by probonopd** [comment]
```
me@host:~$ ./qtquickapp-git.bacf740-x86-64.appimage --appimage-mount
/tmp/.mount_5DG5bM
me@host:~$ /tmp/.mount_5DG5bM/AppRun
```

__DOES__ show the icon on `ubuntu-16.04-desktop-amd64.iso` whereas 

```
me@host:~$ ./qtquickapp-git.bacf740-x86-64.appimage
```
does not.

**Comment by TheAssassin** [comment]
`open()` returns a file descriptor, and that's nothing but a simple integer.
See e.g. http://man7.org/linux/man-pages/man2/open.2.html for more information (or consult your local `man 2 open`).

I assume that the fd counter is increased whenever a new file is opened. That leads to the assumption that Qt internally opens one file less when it doesn't work.

**Comment by probonopd** [comment]
A fuller strace:

```
## Not working when running directly

root@host:/home/me# strace -eopen -f ./qtquickapp-git.bacf740-x86-64.appimage  2>&1 | grep pix -C 5
[pid 12208] open("/usr/share/X11/xkb/symbols/level3", O_RDONLY) = 7
[pid 12208] open("/usr/share/X11/xkb/symbols/level3", O_RDONLY) = 7
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/xcbglintegrations", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 7
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so", O_RDONLY|O_CLOEXEC) = 7
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so", O_RDONLY|O_CLOEXEC) = 7
[pid 12208] open("/tmp/.mount_b7CyL4/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
[pid 12208] open("/usr/share/mime/mime.cache", O_RDONLY|O_CLOEXEC) = 8
[pid 12208] open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 9
[pid 12208] open("/usr/share/mime/types", O_RDONLY|O_CLOEXEC) = 9
[pid 12208] open("/usr/share/mime/image/png.xml", O_RDONLY|O_CLOEXEC) = 7
[pid 12208] open("/tmp/.mount_b7CyL4/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/imageformats", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/imageformats/libqgif.so", O_RDONLY|O_CLOEXEC) = 9
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/imageformats/libqico.so", O_RDONLY|O_CLOEXEC) = 9
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/imageformats/libqjpeg.so", O_RDONLY|O_CLOEXEC) = 9
[pid 12208] open("/tmp/.mount_b7CyL4/usr/plugins/imageformats/libqgif.so", O_RDONLY|O_CLOEXEC) = 9

## Working when running from mounted AppImage

root@host:/home/me# strace -eopen -f /tmp/.mount_5A4ecZ/AppRun 2>&1 | grep pix -C 5
[pid 12172] open("/usr/share/X11/xkb/symbols/level3", O_RDONLY) = 6
[pid 12172] open("/usr/share/X11/xkb/symbols/level3", O_RDONLY) = 6
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/xcbglintegrations", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so", O_RDONLY|O_CLOEXEC) = 6
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so", O_RDONLY|O_CLOEXEC) = 6
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 6
[pid 12172] open("/usr/share/mime/mime.cache", O_RDONLY|O_CLOEXEC) = 7
[pid 12172] open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 8
[pid 12172] open("/usr/share/mime/types", O_RDONLY|O_CLOEXEC) = 8
[pid 12172] open("/usr/share/mime/image/png.xml", O_RDONLY|O_CLOEXEC) = 6
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 6
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/imageformats", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/imageformats/libqgif.so", O_RDONLY|O_CLOEXEC) = 8
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/imageformats/libqico.so", O_RDONLY|O_CLOEXEC) = 8
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/imageformats/libqjpeg.so", O_RDONLY|O_CLOEXEC) = 8
[pid 12172] open("/tmp/.mount_5A4ecZ/usr/plugins/imageformats/libqgif.so", O_RDONLY|O_CLOEXEC) = 8
```

**Comment by TheAssassin** [comment]
Both logs are equal, except for the mountpoint name (which we can ignore for now) and the return values of the `open()` calls. An interesting fact: They're all off by one, i.e. the working one's return values are -1.

**Comment by TheAssassin** [comment]
Just tested the file produced by Travis on my Xubuntu 16.04 desktop. In both cases, I can see QtQuickApp's icon in my task bar.
We should test this with other desktop environments, too, and see if we can narrow down the bug to Ubuntu's Unity DE.

**Comment by TheAssassin** [comment]
```
$ sudo strace -eopen -f ./QtQuickApp-git.bacf740-x86_64.AppImage   2>&1  | grep pix
[pid 25675] open("/tmp/.mount_8mwIOm/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
[pid 25675] open("/tmp/.mount_8mwIOm/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
[pid 25675] open("/usr/share/pixmaps/default/cursors/left_ptr", O_RDONLY) = -1 ENOENT (No such file or directory)
```

To sum up: I get the same return values for the `open()` calls, but the icon works perfectly fine.

![screenshot_2017-03-26_00-33-30](https://cloud.githubusercontent.com/assets/4503202/24326977/dcf1716e-11bb-11e7-9f6d-7e1c559e8c47.png)

**Comment by probonopd** [comment]
For what it is worth, it is working correctly from _inside_ the AppImage on KDE neon User Edition 5.9:

![screenshot_20170326_183009](https://cloud.githubusercontent.com/assets/2480569/24333085/545d007e-1252-11e7-9a0e-78c6b3a9fd6c.png)

```
me@host:~/Downloads$ sudo strace -eopen -f ./qtquickapp-git.bacf740-x86-64.appimage 2>&1  | grep pix
[pid  6152] open("/tmp/.mount_IY43lg/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
[pid  6152] open("/tmp/.mount_IY43lg/usr/share/pixmaps/qtquickapp.png", O_RDONLY|O_CLOEXEC) = 7
```

**Comment by probonopd** [comment]
So in summary, this may be related to __Ubuntu Unity__ only. But why?

**Comment by probonopd** [comment]
@phoerius reports [here](https://github.com/probonopd/AppImageKit/issues/351#issuecomment-289297916):

> But we are also having __similar issues with our Snap package which we haven't yet solved. I suppose this is a general problem with Ubuntu and self-contained app containers.__

**Comment by probonopd** [comment]
Note to self: Try to set/unset `XDG_DATA_DIRS`.

**Comment by probonopd** [comment]
It also works on Ubuntu 14.04 GNOME Edition:

![screenshot from 2017-03-27 08-58-12](https://cloud.githubusercontent.com/assets/2480569/24344394/96ebc6b8-12cb-11e7-95cf-74e752c0dbcf.png)

**Comment by Loxodromics** [comment]
In the latest version the icon works for me in virtual machines with Debian_8.6.0 (Gnome), openSUSE Tumbleweed (KDE) and Ubuntu 16.10 (Unity). But in no case does the icon show in the file manager – even after a restart.
<img width="514" alt="screen shot 2017-03-31 at 16 40 23" src="https://cloud.githubusercontent.com/assets/4097329/24556425/979b9f54-1634-11e7-96d9-1b1da8f78dbe.png">

**Comment by probonopd** [comment]
@Loxodromics the icon in the filemanager is not implemented for type 2 AppImages, see https://github.com/probonopd/AppImageKit/issues/346

**Comment by Loxodromics** [comment]
@probonopd okay, I see, thank you

**Comment by probonopd** [comment]
@phoerious nailed it in 
https://github.com/keepassxreboot/keepassxc/issues/194#issuecomment-278390066

> I finally managed to fix this issue. It appears that Qt resolves icons also in the program's working directory, but Unity doesn't. So when Qt found the icon there, it passes it on to the tray which tries to resolve the path again, but can't find it. __I fixed it by enforcing absolute icon paths for tray icons.__

So, `absoluteFilePath` in this code

```
QFileInfo fi(app.applicationDirPath() + "/../share/pixmaps/qtquickapp.png");
QGuiApplication::setWindowIcon(QIcon(fi.absoluteFilePath()));
```
makes it work on Ubuntu Unity. Thanks @phoerious

![screenshot from 2017-04-01 22-17-48](https://cloud.githubusercontent.com/assets/2480569/24582124/3329d8ec-1729-11e7-8f00-e9ed85e329d8.png)
